version: "3"
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    network_mode: host
    volumes:
      - nginx-proxy-manager_data:/data
      - nginx-proxy-manager_letsencrypt:/etc/letsencrypt

volumes:
  nginx-proxy-manager_data:
  nginx-proxy-manager_letsencrypt: